# apiVersion: v1
# kind: Service
# metadata:
#   creationTimestamp: null
#   labels:
#     app: sq
#     app.kubernetes.io/managed-by: Helm
#   name: sq
# spec:
#   ports:
#   - port: 1433
#     protocol: TCP
#     targetPort: 1433
#     nodePort: 30443
#   selector:
#     app: sq
#   type: NodePort
# status:
#   loadBalancer: {}